#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "convertx"
name = "ConvertX"
description.en = "File conversion utility"
description.fr = "Utilitaire de conversion de fichiers"

version = "0.12.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
code = "https://github.com/C4illin/ConvertX"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/C4illin/ConvertX/archive/refs/tags/v0.12.1.tar.gz"
    sha256 = "5154dd87fdb0a9bfc2ed7cd3d8582d9957a3ef14691514813bda20ce080ff05f"
    #autoupdate.strategy = "latest_github_tags"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
    
    [resources.apt]
    packages = "ffmpeg"


